= Accreditation Status

NOTE: Accreditation requirements for **Ready, Advanced and Premier** partner tier levels are link:https://connect.redhat.com/sites/default/files/legacy/files/programs_RH_solution_provider_NA.pdf?v=3[here] .


[.lead]
*Executive commitment:* 

* To build sustainable Red Hat business - ready to invest required internal resources
* To build and execute comprehensive annual business plan with Red Hat to include:
	** Training plan
	** Engagement plan
	** Marketing plan
	** Net new targets
* (5) Red Hat accreditations plus (1) ET authorization (Ansible or Openshift) within one year
* 3 sales, 1 sales engineer, 1 delivery engineer (or second sales engineer)
* (2) Red Hat solution demand gen campaigns per year (light touch by RHT - digital focus)
* Annual revenue objective = $250K SYB New subs


**Advanced Build Partner Requirements**:   
================================================
**1.)** Have approved annual growth plan to qualify 
=================================================
**2.)** Complete minimum accreditation requirements for Advanced (1-2/1) within first 120 days and sell minimum $100K subs within one year in order to retain Advanced status and remain active in Advanced Build initiative.
=================================================
**3.)** Five accreditations must come from five different resources
=================================================

**Premier Partner Requirements** 

*Link to course catalog:* 

link::https://www.redhat.com/en/partners/course_catalog

[.lead]
Example Advanced Partner with Automation Accreditation

Choose one of the following

*Option 1 - I.T. Optimization Track:* course names

   2 SALES - Red Hat Sales Specialist - I.T. Optimization
   1 SALES ENGINEER - Red Hat Sales Engineer Specialist - Platform
   1 DELIVERY - Red Hat Delivery Specialist – Platform

                                   *OR*

*Option 2 - I.T. Automation + Management Track:* course names

   2 SALES – Red Hat Sales Specialist - I.T. Automation & Management
   1 SALES ENGINEER – Red Hat Sales Engineer Specialist - Automation
   1 DELIVERY - Red Hat Delivery Specialist - Automation I

*For more details please reach out to Partner Account Manager*

