= Areas of Focus



=============================================================================
[.text-left]
[big]##**+++<u>Workshops</u>+++**##

As a member of the **Advanced Partner Enablement** organization you will have access to the **Red Hat Product Demo System (RHPDS)**, a tool exclusive to Red Hat employees and Red Hat partners.

This tool contains **Content created by Red Hat technical experts** and **spans the entire Red Hat product portfolio**,  including multi-product solutions.

These workshops have been customized to provide a **variety of customer experiences ranging from 1-2 hours or 1-2 days**.

NOTE: You can get started with RHPDS by clicking this link:using_red_hat_rhpds.adoc[LINK]
=============================================================================

=============================================================================
[.text-left]
[big]##**+++<u>Reference Architectures</u>+++**##

If you are looking for a **complete list of Red Hat Reference Architectures** please visit the link below:

* link:https://access.redhat.com/documentation/en-us/reference_architectures/current/[Product Documentation for Reference Architectures,window=_blank]

=============================================================================

=============================================================================
[.text-left]
[big]##**+++<u>Subscription Guide</u>+++**##

Are you looking for information about Red Hat Subscriptions???

The following links provide data around Red Hat subscriptions and their value!!!


* link:https://www.redhat.com/en/resources/red-hat-enterprise-linux-subscription-guide[Red Hat Enterprise Linux Subscription Guide,window=_blank]

* link:https://www.redhat.com/en/about/subscription-model-faq[Subscription Model FAQ,window=_blank]

* link:https://www.redhat.com/en/about/value-of-subscription[Value of a Red Hat Subscription,window=_blank]

=============================================================================

=============================================================================
[.text-left]
[big]##**+++<u>Red Hat Blogs</u>+++**##

The **strength of Red Hat** is in our **community of passionate people** and the ideas of these enthusiasts, customers, partners, and Red Hats leaders. Hear from them directly in our blogs.

To see and search **all the Red Hat Blogs** click on the link below:

* link:https://www.redhat.com/en/all-blogs[All Red Hat Blogs,window=_blank]

=============================================================================
